# Generated by Django 3.2.4 on 2021-07-14 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codex', '0004_auto_20210703_1821'),
        ('profiles', '0002_auto_20210709_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCharacters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('current_xp', models.IntegerField(default=0)),
                ('battle_count', models.IntegerField(default=0)),
                ('char_hp', models.IntegerField()),
                ('char_attack', models.IntegerField()),
                ('char_defense', models.IntegerField()),
                ('char_speed', models.IntegerField()),
                ('weapon_hp', models.IntegerField()),
                ('weapon_attack', models.IntegerField()),
                ('weapon_defense', models.IntegerField()),
                ('weapon_speed', models.IntegerField()),
                ('weapon_level', models.IntegerField()),
                ('weapon_rarity', models.CharField(choices=[('1', 'Common'), ('2', 'Uncommon'), ('3', 'Rare'), ('4', 'Epic'), ('5', 'Mythic')], default='1', max_length=10)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='codex.codex')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='codex.codex')),
            ],
        ),
    ]
