# Generated by Django 3.2.4 on 2021-07-14 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codex', '0004_auto_20210703_1821'),
        ('profiles', '0003_activecharacters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveCharacters',
            new_name='ActiveCharacter',
        ),
        migrations.AlterModelOptions(
            name='activecharacter',
            options={'verbose_name_plural': 'Active Characters'},
        ),
    ]
