# Generated by Django 3.2.4 on 2021-07-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_activecharacter_weapon_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecharacter',
            name='max_xp',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='activecharacter',
            name='min_xp',
            field=models.IntegerField(default=0),
        ),
    ]
