# Generated by Django 3.2.4 on 2021-07-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alpha_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('EN', 'Enemy'), ('WE', 'Weapon'), ('HE', 'Hero')], default='EN', max_length=2)),
                ('base_hp', models.IntegerField(default=5)),
                ('base_attack', models.IntegerField(default=5)),
                ('base_defense', models.IntegerField(default=5)),
                ('base_speed', models.IntegerField(default=5)),
                ('image', models.ImageField(upload_to='')),
                ('paid', models.BooleanField(default=False)),
                ('min_level', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
            ],
        ),
    ]
