# Generated by Django 3.2.4 on 2021-07-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_alter_codex_min_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codex',
            name='min_level',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
