# Generated by Django 3.2.4 on 2021-07-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_alter_codex_min_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codex',
            options={'verbose_name_plural': 'Codex'},
        ),
        migrations.AlterField(
            model_name='codex',
            name='type',
            field=models.CharField(choices=[('Enemy', 'Enemy'), ('Weapon', 'Weapon'), ('Hero', 'Hero')], default='Enemy', max_length=10),
        ),
    ]
