# Generated by Django 3.2.4 on 2021-07-18 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codex', '0004_auto_20210703_1821'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('current_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('battle_count', models.IntegerField()),
                ('char_hp', models.IntegerField()),
                ('char_attack', models.IntegerField()),
                ('char_defense', models.IntegerField()),
                ('char_speed', models.IntegerField()),
                ('weapon_hp', models.IntegerField()),
                ('weapon_attack', models.IntegerField()),
                ('weapon_defense', models.IntegerField()),
                ('weapon_speed', models.IntegerField()),
                ('weapon_level', models.IntegerField(default=1)),
                ('weapon_rarity', models.CharField(choices=[('1', 'Common'), ('2', 'Uncommon'), ('3', 'Rare'), ('4', 'Epic'), ('5', 'Mythic')], default='1', max_length=10)),
                ('character_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_character', to='codex.codex')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('weapon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_weapon', to='codex.codex')),
            ],
            options={
                'verbose_name_plural': 'Leaderboard',
            },
        ),
    ]
