# Generated by Django 3.2.4 on 2021-07-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codex', '0004_auto_20210703_1821'),
        ('profiles', '0005_alter_activecharacter_weapon_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_hp', models.IntegerField()),
                ('enemy_attack', models.IntegerField()),
                ('enemy_defense', models.IntegerField()),
                ('enemy_speed', models.IntegerField()),
                ('enemy_level', models.IntegerField()),
                ('weapon_hp', models.IntegerField()),
                ('weapon_attack', models.IntegerField()),
                ('weapon_defense', models.IntegerField()),
                ('weapon_speed', models.IntegerField()),
                ('weapon_level', models.IntegerField(default=1)),
                ('weapon_rarity', models.CharField(choices=[('1', 'Common'), ('2', 'Uncommon'), ('3', 'Rare'), ('4', 'Epic'), ('5', 'Mythic')], default='1', max_length=10)),
                ('active_character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.activecharacter')),
                ('enemy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='codex.codex')),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_weapon', to='codex.codex')),
            ],
            options={
                'verbose_name_plural': 'Active Enemies',
            },
        ),
    ]
